language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - "pip install -r cli/requirements.txt"
  - "pip install tox-travis"
# command to run tests
script:
  - "cd cli"
  - "tox"
after_success: codeclimate-test-reporter
